### PR TITLE
Fix type confusion in Falcon-512/1024 in aarch64 implementation

### PR DESCRIPTION
**Pull request by cothan**
There is a compiler error while pulling from pqclean to liboqs. 

https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs/2788/workflows/46cbb0ce-3a37-4cfb-ba32-a33f2bced86f/jobs/22376 

This PR fix the type confusion and eliminate compiler error, also make the liboqs CI/CD green, as in https://github.com/open-quantum-safe/liboqs/pull/1547

### CODE REVIEW

**Comment by cothan** [comment]
It's strange. Some tests are red, the bug is unrelated to my PR.

**Comment by thomwiggers** [comment]
Ugh, it seems the tests break due to pip3's behaviour having changed. I suppose we'll set up another PR

**Comment by thomwiggers** [comment]
Rebasing on `master` should help with the CI, but these implementations aren't actually run anyway.

**Comment by thomwiggers** [comment]
Checked `test_functest` manually

**Pull request merged**
