### PR TITLE
Use 5 iterations for functional tests and test vectors

### LINKED ISSUE #85: Reduce number of iterations
Reduce number of iterations in functest and testvectors to say 5.

### PR DESCRIPTION
**Pull request by dstebila**
Fixes #85.

## Manually checked properties

* [ ] `#ifdef`s only for header encapsulation
* [ ] `api.h` does not include other files
* [ ] No stringification macros
* [ ] Output-parameter pointers in functions are on the left
* [ ] Negative return values on failure of API functions (within restrictions of FO transform).
* [ ] `const` arguments are labeled as `const`
* [ ] variable declarations at the beginning (except in `for (size_t i=...`)
* Optional:
  * [ ] All integer types are of fixed size, using `stdint.h` types (including `uint8_t` instead of `unsigned char`)
  * [ ] Integers used for indexing are of size `size_t`

### CODE REVIEW

**Comment by dstebila** [comment]
There's something weird in `test/crypto_sign/testvectors.c` which I wasn't sure how to fix.  The `NTESTS` macro isn't being used to control the number of tests, instead there's `MAXMLEN`.  @mkannwischer you wrote this originally, can you help?

**Comment by joostrijneveld** [comment]
I just ran into the same thing w.r.t. detached signatures. I'll give it a shot.

**Comment by dstebila** [comment]
I'm still confused -- what does that code actually do?

**Comment by joostrijneveld** [comment]
I believe it generates several signatures, for increasing message lengths up to `MAXMLEN`, increasing the length exponentially.

**Comment by dstebila** [comment]
> I believe it generates several signatures, for increasing message lengths up to `MAXMLEN`, increasing the length exponentially.

Makes sense, thanks!

**Comment by joostrijneveld** [comment]
Hmm, this is probably not the right place for `gen_testvector_hash.py`; now nose picks it up as a test. That should probably live somewhere else, but that requires some edits w.r.t. relative imports. I'll look at that tonight/tomorrow.

**Comment by thomwiggers** [comment]
> now nose picks it up as a test

I think there's some logic to that, if you change the names or make the file executable it should be ignored.

https://nose.readthedocs.io/en/latest/finding_tests.html

**Comment by dstebila** [comment]
Do we really need gen_testvector_hash.py?  I just did 

    bin/testvectors_frodo640kemshake_clean | sha256sum

and copied the output.

**Comment by cryptojedi** [comment]
Douglas Stebila <notifications@github.com> wrote:
> Do we really need gen_testvector_hash.py?  I just did 
> 
>     bin/testvectors_frodo640kemshake_clean | sha256sum
> 
> and copied the output.

I agree, that's probably the easiest thing to do.

**Comment by joostrijneveld** [comment]
Right, I clearly didn't think this through and went autopilot based on `test/test_testvectors.py`; I removed the script again.

**Pull request merged**
