### PR TITLE
Remove schemes that are no longer under consideration by NIST

### LINKED ISSUE #139: Add Round 3 alternative signature scheme GeMSS

### LINKED ISSUE #143: Add Round 3 signature scheme Picnic

### LINKED ISSUE #443: MSVC: missing support for AVX bitwise operators
The AVX implementation (sntrup761\avx2) fails to build on MSVC because the compiler doesn't support operators:

For example in sntrup761\avx2\crypto_decode_761x4591.c:
```
    return sub(x, _mm256_cmpgt_epi16(x, top16) & y16);
```

Error:
```
sntrup761\avx2\crypto_decode_761x4591.c(47,48): error C2088: '&': illegal for union
```

The operators need to be replaced with intrinsics:
_mm256_and_si256
_mm256_or_si256
_mm256_xor_si256

PR: https://github.com/PQClean/PQClean/pull/444

### PR DESCRIPTION
**Pull request by mkannwischer**
See https://csrc.nist.gov/projects/post-quantum-cryptography/round-4-submissions

Closes #143 
Closes #139 
Closes #443 
Closes #444

### CODE REVIEW

**Comment by thomwiggers** [comment]
Is there anything we want to fix in these schemes before we create the R3 tag in the repository and merge this commit?

**Review by thomwiggers — CHANGES_REQUESTED** [review]
Can you `rm .github/workflows/{kem,sign}_*.yml` and then run the script in `.github/workflows` to prune and re-generate all the workflows?

**Comment by mkannwischer** [comment]
> Can you `rm .github/workflows/{kem,sign}_*.yml` and then run the script in `.github/workflows` to prune and re-generate all the workflows?

done.

**Review by thomwiggers — APPROVED** [review]

**Comment by thomwiggers** [comment]
🤔 why did only 26 tests run

**Comment by thomwiggers** [comment]
ah, never mind, they obviously just don't run because we only removed schemes and did not touch the tests.

**Pull request merged**
