### PR TITLE
Add test to cross-check OBJECTS between Makefiles

### LINKED ISSUE #99: We might want to add a test that Makefile and Makefile.Microsoft_nmake want the same object files

### PR DESCRIPTION
**Pull request by joostrijneveld**
Fixes #99

### CODE REVIEW

**Comment by thomwiggers** [comment]
This does mean that you're hardcoding that people need to define exactly OBJECTS as a variable.

**Comment by joostrijneveld** [comment]
I don't have a problem with that - in fact, I wouldn't mind enforcing a much stronger template on the Makefile, i.e., essentially only let implementations differ in `HEADERS` and `OBJECTS`.

Briefly talked to @cryptojedi about this yesterday; the main argument against including the common build targets is to keep the makefiles self-contained -- I guess we've all seen a project or two where you find yourself to tracing Makefile-includes for half an hour.

**Comment by dstebila** [comment]
Do we really need this?  There's already a check that every .c / .h file is used by Makefile, and both Makefile and Makefile.Microsoft_nmake are exercised by the CI system.  I don't see any security risk arising from these two Makefiles being slightly out-of-sync.  So to me this could be upping the annoyance factor for contributors.

**Comment by joostrijneveld** [comment]
The motivation that led up to this was a typo that this test would've caught when developing on Linux and only testing on Windows on CI.. but yeah, in hindsight I agree that it's clutter. These errors will be caught by CI, and that's fine.

**Pull request closed without merging**
