### PR TITLE
Add GeMSS

### LINKED ISSUE #139: Add Round 3 alternative signature scheme GeMSS

### PR DESCRIPTION
**Pull request by jschanck**
Will resolve #139 

* [ ] No stringification macros
* [ ] Output-parameter pointers in functions are on the left
* [ ] Negative return values on failure of API functions (within restrictions of FO transform).
* [ ] variable declarations at the beginning (except in `for (size_t i=...`)
* Optional:
  * [ ] All integer types are of fixed size, using `stdint.h` types (including `uint8_t` instead of `unsigned char`)
  * [ ] Integers used for indexing are of size `size_t`

### CODE REVIEW

**Comment by jschanck** [comment]
I'm not sure how to proceed here without dynamic memory. The public keys for the 256 bit parameter sets are ~3MB, and this implementation ends up needing around 18 MB of stack space. Tests are failing because of the standard 8MB limit. The function changeVariablesMQS_simd_gf2, which computes a matrix map Q -> S*Q*S^t, is the main optimization target.

**Comment by thomwiggers** [comment]
Not entirely unexpected that we would run into this at some point down the line. OQS has had stack-space trouble in the past already... 

How much stack is used if the pubkeys are moved into `malloc()`'d memory in the tests?

**Comment by jschanck** [comment]
For gemss-256, we have
> nistkat (~3MB)
>> sign_keypairHFE (6.7MB)
>>> changeVariablesMQS_gf2 (7.2MB)

I can probably cut the usage of the two inner routines in half. We'd still need to switch to malloc in the tests.

**Comment by thomwiggers** [comment]
CI has been refactored to build on Github Actions. Would you mind rebasing this PR on master and generating the workflow files for Github Actions (see `.github/workflows/generate_workflows.py`)? Sorry for the inconvenience.

**Comment by jschanck** [comment]
The 128- and 192-bit parameter sets are good to go once we get a LICENSE file. I've reached out to two members of the GeMSS team about it and haven't heard back.

**Comment by thomwiggers** [comment]
Have you heard back about the license?

**Comment by jschanck** [comment]
I have not, and I'm not going to make any further attempts. Suggest closing this unless someone else wants to take over.

**Comment by thomwiggers** [comment]
I've reached out to Ludovic Perret.

**Comment by thomwiggers** [comment]
I've bumped the email

**Pull request closed without merging**
