### PR TITLE
Fix NewHope CCA verify function

### LINKED ISSUE #269: Bug in NewHope CCA verify function
https://github.com/mupq/pqm4/issues/132 reports a bug in the NewHope verify function that was introduced by me by adding a wrong cast when integrating it into PQClean. 
Sorry about that. I'll fix this asap.

### PR DESCRIPTION
**Pull request by mkannwischer**
Fixes #269.
https://github.com/mupq/pqm4/issues/132 reported that the NewHope verify function does not actually return 0 or 1, but 0 or -1, which consequently breaks the cmov in the FO transform (in case of a re-encryption failure). 
This bug was introduced when I integrated this into PQClean. I added a wrong cast. Without the cast, it works correctly on my machine. 
If I recall correctly, this failed on some of the other platforms. Let's see.

### CODE REVIEW

**Comment by mkannwischer** [comment]
Somehow all the tests got skipped in our Windows builds. Any ideas @thomwiggers?

**Comment by thomwiggers** [comment]
That's strange indeed, no idea...

**Comment by thomwiggers** [comment]
I'm logged in via RDP on one of the Appveyor boxes, trying to run `permit_test`, but that says that it should be working...

**Comment by thomwiggers** [comment]
the problem is that the paths returned by `git` use forward slashes, and the paths on Windows are backslashes... so the `PQCLEAN_ONLY_DIFF` helper things it's not one of the changed paths.

**Comment by thomwiggers** [comment]
```
verify.c(25): error C2220: the following warning is treated as an error
verify.c(25): warning C4146: unary minus operator applied to unsigned type, result still unsigned
```

**Comment by thomwiggers** [comment]
If you rebase on master to include #277 it'll pass

**Comment by thomwiggers** [comment]
Rebased and force-pushed

**Pull request merged**
