### PR TITLE
Only absorb root part of pk in haraka message hashing.

### PR DESCRIPTION
**Pull request by kste**
Fix to only absorb root part of the pk in the message hash of Haraka, as required in the NIST specification.

#### Manually checked properties

* [ ] No stringification macros
* [ ] Output-parameter pointers in functions are on the left
* [ ] Negative return values on failure of API functions (within restrictions of FO transform).
* [ ] `const` arguments are labeled as `const`
* [ ] variable declarations at the beginning (except in `for (size_t i=...`)
* Optional:
  * [ ] All integer types are of fixed size, using `stdint.h` types (including `uint8_t` instead of `unsigned char`)
  * [ ] Integers used for indexing are of size `size_t`

### CODE REVIEW

**Comment by thomwiggers** [comment]
Appveyor is probably just being weird.

**Comment by thomwiggers** [comment]
Tests are also not run for SPHINCS+ at the moment (once #206 gets merged we might include it again) – so we should make sure to tests this locally.

**Comment by dstebila** [comment]
> This changes the KAT and testvector values, so the META files should be updated.

Why are the KAT values changing?  Did the specification change, or did our implementation not match the specification?

**Comment by thomwiggers** [comment]
Apparently the SPHINCS+ team made a small mistake. They also made this change in their canonical repository: https://github.com/sphincs/sphincsplus/commit/0208952716af0e023e91f2a64668ce125aa40090

**Comment by thomwiggers** [comment]
I've pushed new hashes; will now run tests on a server somewhere. Should be able to collect the results and press the merge button tomorrow.

**Pull request merged**
