### PR TITLE
Update Classic McEliece

### LINKED ISSUE #459: Upgrade Classic McEliece to NIST round 4 specification
Hi! Are there any plans to upgrade the Classic McEliece KEM to the [round 4 specification](https://classic.mceliece.org/nist.html)? I suppose it will be done. But I could not find any issue or PR on it. So I figured I could create this tracking issue.

### PR DESCRIPTION
**Pull request by thomwiggers**
This updates classic mceliece to the SUPERCOP-20221025 version. I'm generating this version from the SUPERCOP source code, and apply patches that are listed in the repository below.

Some of the found code flaws have been reported to the submission team.

The repository where this codes is coming from can be found at
https://github.com/thomwiggers/mceliece-clean in the update-mceliece branch.

Closes #459 

## Additional content
* I'm adding VLA support through a header (#462)
* I'm adding a `crypto_declassify.h` dummy header for TIMECOP support. (#463)
* I'm dropping the `vec` and `sse` implementations of Classic McEliece.

#### Manually checked properties
* [x] Generated Github workflow (run ``.github/workflows/generate_workflows.py``) (new schemes)
* [x] No stringification macros
* [ ] Output-parameter pointers in functions are on the left
   * This would require large amounts of changes that I'm not sure are worth it
* [ ] Negative return values on failure of API functions (within restrictions of FO transform).
* [x] variable declarations at the beginning (except in `for (size_t i=...`)
* Optional:
  * [ ] All integer types are of fixed size, using `stdint.h` types (including `uint8_t` instead of `unsigned char`)
  * [ ] Integers used for indexing are of size `size_t`

### CODE REVIEW

**Comment by thomwiggers** [comment]
* I'm not sure why so many schemes trigger in CI, but alas
* I need to fix some warnings generated by Clang still.

**Comment by dstebila** [comment]
What's the best approach for me to review this?

**Comment by thomwiggers** [comment]
Apparently the tests now fail due to a bug in Valgrind (#468). 

With regards to reviewing these changes:  that depends how much code you want to review. The Classic McEliece code probably has some rough edges still (but fixing them will be a lot rougher) than the small fixes done so far. If you want to review my patches, I suggest looking at the patches https://github.com/thomwiggers/mceliece-clean/tree/update-mceliece/patches

**Comment by thomwiggers** [comment]
Continued in #469. Apparently you can't reopen a PR after force-pushing to the branch. (I was trying to clean the cache of changed files...)

**Pull request closed without merging**
