### PR TITLE
Pull Dilithium changes from upstream

### PR DESCRIPTION
**Pull request by jschanck**
Update to pq-crystals/dilithium@adf7476d645fb808b5c5d2dd1ef1aaeefdc0c897

### CODE REVIEW

**Review by thomwiggers — APPROVED** [review]

**Comment by jschanck** [comment]
@thomwiggers, I'll tack on a fix for #372 if you hold off on merging.

**Comment by jschanck** [comment]
@thomwiggers this is ready to go

**Review by thomwiggers — APPROVED** [review]
The `memmove` is not the best solution for the `fips202x4` code, but it'll do.

**Comment by thomwiggers** [comment]
Thanks a lot @jschanck

**Comment by jschanck** [comment]
I didn't benchmark but the assembly produced by clang at O3 looked pretty good.

**Comment by thomwiggers** [comment]
Compilers saving the day

**Pull request merged**
