### PR TITLE
Fix mismatching function signature in Classic McEliece

### LINKED ISSUE #412: McEliece doesn't compile with GCC 11
As identified in open-quantum-safe/liboqs#1035 and open-quantum-safe/liboqs#1036, Classic McEliece doesn't compile with GCC 11 due to mismatching function signatures:

```
FAILED: src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/fft_tr.c.o
/usr/bin/cc  -Iinclude -I../src/kem/classic_mceliece/pqclean_mceliece348864_avx -I../src/common/pqclean_shims -fPIC -fvisibility=hidden -march=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -mavx2 -mpopcnt -Wno-language-extension-token -std=gnu11 -MD -MT src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/fft_tr.c.o -MF src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/fft_tr.c.o.d -o src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/fft_tr.c.o -c ../src/kem/classic_mceliece/pqclean_mceliece348864_avx/fft_tr.c
../src/kem/classic_mceliece/pqclean_mceliece348864_avx/fft_tr.c:351:47: error: argument 1 of type ‘vec128[12]’ {aka ‘__m128i[12]’} with mismatched bound [-Werror=array-parameter=]
  351 | void PQCLEAN_MCELIECE348864_AVX_fft_tr(vec128 out[GFBITS], vec256 in[][ GFBITS ]) {
      |                                        ~~~~~~~^~~~~~~~~~~
In file included from ../src/kem/classic_mceliece/pqclean_mceliece348864_avx/fft_tr.c:6:
../src/kem/classic_mceliece/pqclean_mceliece348864_avx/fft_tr.h:11:40: note: previously declared as ‘vec128 *’ {aka ‘__m128i *’}
   11 | void PQCLEAN_MCELIECE348864_AVX_fft_tr(vec128 * /*out*/, vec256  /*in*/[][ GFBITS ]);
      |                                        ^~~~~~~~
```

### PR DESCRIPTION
**Pull request by dstebila**
Fixes #412.

### CODE REVIEW

**Comment by dstebila** [comment]
This PR is actually nowhere near complete, apparently the same signature mismatch appears in most/all of the McEliece variants and implementations.  Is going to require a lot more work to fix.  Before I embark on this, is this implementation being pulled from an upstream or is it only here now?  

Also, not sure why the sse tests are failing -- I didn't touch anything in the sse folder.

**Comment by dstebila** [comment]
> This PR is actually nowhere near complete, apparently the same signature mismatch appears in most/all of the McEliece variants and implementations. Is going to require a lot more work to fix. Before I embark on this, is this implementation being pulled from an upstream or is it only here now?

@mkannwischer Are you the expert on the McEliece implementation? If so can you answer my question above?

**Comment by mkannwischer** [comment]
No, I have not touched McEliece so far. Looking at https://github.com/PQClean/PQClean/pull/259, it seems @thomwiggers added these implementations using https://github.com/thomwiggers/mceliece-clean which looks like SUPERCOP to me.

**Comment by dstebila** [comment]
Okay, I'll wait till Thom gets back.

**Comment by thomwiggers** [comment]
> No, I have not touched McEliece so far. Looking at #259, it seems @thomwiggers added these implementations using https://github.com/thomwiggers/mceliece-clean which looks like SUPERCOP to me.

This repo is quite out of date with the upstream (supercop) code though, as well as with our current state of the code, and the diffs were not trivial...  So I don't think it's worth applying it there. (the only way in which that repo reduces having to change multiple files is symlinks, which is still quite painful to edit because you're not sure what's symlinked)

**Comment by dstebila** [comment]
> > No, I have not touched McEliece so far. Looking at #259, it seems @thomwiggers added these implementations using https://github.com/thomwiggers/mceliece-clean which looks like SUPERCOP to me.
> 
> This repo is quite out of date with the upstream (supercop) code though, as well as with our current state of the code, and the diffs were not trivial... So I don't think it's worth applying it there. (the only way in which that repo reduces having to change multiple files is symlinks, which is still quite painful to edit because you're not sure what's symlinked)

Understood, I'll focus on making changes directly into PQClean.

**Comment by dstebila** [comment]
This should be ready to review and merge, @thomwiggers.

**Pull request merged**
