### PR TITLE
NTRU: fix input type documentation mismatch

### LINKED ISSUE #411: NTRU doesn't compile with GCC 11
As identified in https://github.com/open-quantum-safe/liboqs/issues/1035, NTRU doesn't compile with GCC 11 due to mismatching function signatures:

```
FAILED: src/kem/ntru/CMakeFiles/ntru_hps2048677_avx2.dir/pqclean_ntruhps2048677_avx2/pack3.c.o
/usr/bin/cc  -Iinclude -I../src/kem/ntru/pqclean_ntruhps2048677_avx2 -I../src/common/pqclean_shims -fPIC -fvisibility=hidden -march=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -mavx2 -mbmi2 -std=gnu11 -MD -MT src/kem/ntru/CMakeFiles/ntru_hps2048677_avx2.dir/pqclean_ntruhps2048677_avx2/pack3.c.o -MF src/kem/ntru/CMakeFiles/ntru_hps2048677_avx2.dir/pqclean_ntruhps2048677_avx2/pack3.c.o.d -o src/kem/ntru/CMakeFiles/ntru_hps2048677_avx2.dir/pqclean_ntruhps2048677_avx2/pack3.c.o -c ../src/kem/ntru/pqclean_ntruhps2048677_avx2/pack3.c
../src/kem/ntru/pqclean_ntruhps2048677_avx2/pack3.c:3:64: error: argument 1 of type ‘unsigned char[272]’ with mismatched bound [-Werror=array-parameter=]
    3 | void PQCLEAN_NTRUHPS2048677_AVX2_poly_S3_tobytes(unsigned char msg[NTRU_OWCPA_MSGBYTES], const poly *a) {
      |                                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/kem/ntru/pqclean_ntruhps2048677_avx2/pack3.c:1:
../src/kem/ntru/pqclean_ntruhps2048677_avx2/poly.h:25:64: note: previously declared as ‘unsigned char[136]’
   25 | void PQCLEAN_NTRUHPS2048677_AVX2_poly_S3_tobytes(unsigned char msg[NTRU_PACK_TRINARY_BYTES], const poly *a);
      |                                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/kem/ntru/pqclean_ntruhps2048677_avx2/pack3.c:24:81: error: argument 2 of type ‘const unsigned char[272]’ with mismatched bound [-Werror=array-parameter=]
   24 | void PQCLEAN_NTRUHPS2048677_AVX2_poly_S3_frombytes(poly *r, const unsigned char msg[NTRU_OWCPA_MSGBYTES]) {
      |                                                             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/kem/ntru/pqclean_ntruhps2048677_avx2/pack3.c:1:
../src/kem/ntru/pqclean_ntruhps2048677_avx2/poly.h:26:81: note: previously declared as ‘const unsigned char[136]’
   26 | void PQCLEAN_NTRUHPS2048677_AVX2_poly_S3_frombytes(poly *r, const unsigned char msg[NTRU_PACK_TRINARY_BYTES]);
      |                                                             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

and also:

```
../src/kem/ntru/pqclean_ntruhps4096821_avx2/pack3.c:3:64: error: argument 1 of type 'unsigned char[328]' with mismatched bound [-Werror=array-parameter=]
    3 | void PQCLEAN_NTRUHPS4096821_AVX2_poly_S3_tobytes(unsigned char msg[NTRU_OWCPA_MSGBYTES], const poly *a) {
      |                                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/kem/ntru/pqclean_ntruhps4096821_avx2/pack3.c:1:
../src/kem/ntru/pqclean_ntruhps4096821_avx2/poly.h:25:64: note: previously declared as 'unsigned char[164]'
   25 | void PQCLEAN_NTRUHPS4096821_AVX2_poly_S3_tobytes(unsigned char msg[NTRU_PACK_TRINARY_BYTES], const poly *a);
      |                                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/kem/ntru/pqclean_ntruhps4096821_avx2/pack3.c:17:81: error: argument 2 of type 'const unsigned char[328]' with mismatched bound [-Werror=array-parameter=]
   17 | void PQCLEAN_NTRUHPS4096821_AVX2_poly_S3_frombytes(poly *r, const unsigned char msg[NTRU_OWCPA_MSGBYTES]) {
      |                                                             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/kem/ntru/pqclean_ntruhps4096821_avx2/pack3.c:1:
../src/kem/ntru/pqclean_ntruhps4096821_avx2/poly.h:26:81: note: previously declared as 'const unsigned char[164]'
   26 | void PQCLEAN_NTRUHPS4096821_AVX2_poly_S3_frombytes(poly *r, const unsigned char msg[NTRU_PACK_TRINARY_BYTES]);
      |                                                             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

and possibly elsewhere.

Tagging @jschanck

### PR DESCRIPTION
**Pull request by jschanck**
Resolves #411

### CODE REVIEW

**Comment by jschanck** [comment]
I don't have gcc-11, so please confirm that this fixes the issue before merging.

**Comment by dstebila** [comment]
They all pass for me with gcc-11.

**Comment by jschanck** [comment]
Context on last commit:

The first run of tests I did failed due to linker errors on powerpc.
```
/usr/bin/ld: /usr/lib/gcc/powerpc-linux-gnu/10/libasan.so: undefined reference to `__atomic_load_8'
```
The same errors show up in tests for #417.

Looks like when libasan was built for debian powerpc the compiler wasn't able to inline all of the atomic loads/stores, so the library has a dependency on libatomic. The compiler should really handle linking with libatomic for us... but it doesn't. So I added an explicit '-latomic' and also told the compiler not to complain if it doesn't end up needing libatomic.

Open to suggestions, but I think it's tricky to handle nicely without a more powerful build system.

**Comment by jschanck** [comment]
The failures above are unrelated to this PR. I opened #419 to track the SPHINCS issues. The McEliece ones should show up in future runs for #417.

**Comment by dstebila** [comment]
I will merge this since the failures are unrelated to this issue and are now tracked elsewhere.  Thanks very much John!

**Pull request merged**
