### PR TITLE
Update SPHINCS+

### PR DESCRIPTION
**Pull request by thomwiggers**
Updates SPHINCS+ from upstream using https://github.com/thomwiggers/sphincsplus/tree/pqclean-export
## To do
- [x] Update duplicate consistency files
- [x] Get correct commit hash in META.yml files

#### Manually checked properties
* [x] Generated Github workflow (run ``.github/workflows/generate_workflows.py``) (new schemes)
* [ ] No stringification macros
* [ ] Output-parameter pointers in functions are on the left
* [ ] Negative return values on failure of API functions (within restrictions of FO transform).
* [ ] variable declarations at the beginning (except in `for (size_t i=...`)
* Optional:
  * [ ] All integer types are of fixed size, using `stdint.h` types (including `uint8_t` instead of `unsigned char`)
  * [ ] Integers used for indexing are of size `size_t`

### CODE REVIEW

**Comment by thomwiggers** [comment]
It seems all tests pass, except for certain instantiations of `test_functest_sanitizers`, which apparently likes to hang on ARMv7...

**Comment by xvzcf** [comment]
In an `arm32v7/debian:bullseye-slim` Docker container, when I build `functest` with `sphincs-sha256-128s-robust` using:

```
make  CC=gcc \
      TYPE=sign \
      SCHEME=sphincs-sha256-128s-robust \
      IMPLEMENTATION=clean \
      EXTRAFLAGS='-g -fsanitize=address,undefined -fno-sanitize-recover=undefined -Wno-unused-command-line-argument -latomic' \
      functest
```

and then run: 

```
env ASAN_OPTIONS='detect_leaks=0' /PQClean/bin/functest_sphincs-sha256-128s-robust_clean:
```

I get:

```
AddressSanitizer: CHECK failed: asan_poisoning.cpp:36 "((AddrIsInMem(addr))) != (0)" (0x0, 0x0) (tid=3472)
    #0 0x3f2a06c6  (/usr/lib/arm-linux-gnueabihf/libasan.so.8+0x906c6)
    #1 0x3f2b8b26  (/usr/lib/arm-linux-gnueabihf/libasan.so.8+0xa8b26)
    #2 0x3f29a428  (/usr/lib/arm-linux-gnueabihf/libasan.so.8+0x8a428)
    #3 0x3f23084c  (/usr/lib/arm-linux-gnueabihf/libasan.so.8+0x2084c)
    #4 0x3f230c00  (/usr/lib/arm-linux-gnueabihf/libasan.so.8+0x20c00)
    #5 0x3f230c8a  (/usr/lib/arm-linux-gnueabihf/libasan.so.8+0x20c8a)
    #6 0x3f2321ca  (/usr/lib/arm-linux-gnueabihf/libasan.so.8+0x221ca)
    #7 0x3f22f562  (/usr/lib/arm-linux-gnueabihf/libasan.so.8+0x1f562)
    #8 0x3f298c9a  (/usr/lib/arm-linux-gnueabihf/libasan.so.8+0x88c9a)
    #9 0x40059b68  (/PQClean/bin/functest_sphincs-sha256-128s-robust_clean+0x59b68)
    ... clipped

```

I don't get this error on `arm64v8/debian:bullseye-slim`; What do you make of this @thomwiggers?

**Comment by thomwiggers** [comment]
I've been seeing similar things, and not just with SPHINCS+ but also in e.g. Kyber. I think ASAN is bugged somehow, so maybe we should just disable this test?

**Comment by xvzcf** [comment]
I repeated it with this branch and `sha2-128s-robust_clean` and got the same result; I also don't have anything better other than chalking this up to a sanitizer bug and moving on; there are disables already in place for Clang, the leak sanitizer, etc. so I guess one more doesn't hurt.

**Comment by dstebila** [comment]
I've pushed a PR that skips SPHINCS+-SHAKE and SPHINCS+-SHA2 on armhf with gcc.

**Comment by thomwiggers** [comment]
Okay I  can't click the approve button on this PR but I think we're ready to merge now?

**Review by dstebila — APPROVED** [review]

**Pull request merged**
