### PR TITLE
Use opaque structs for the hashing API

### LINKED ISSUE #171: Incremental hash API constants
The incremental hashing APIs provided by the `common/` directory appear to be doing some assumptions. For example, the incremental hashing API for SHA256 assumes a state of 40 bytes.

Aside from this not being documented, this also leads to some difficulties if anyone wants to substitute the SHA256 implementation. I am trying to replace SHA2 by the Rust Sha2 crate, but because this implementation has a slightly different structure the state is some bytes larger.

I'd propose introducing some constants like `PQCLEAN_SHA2_INCREMENTAL_STATE_BYTES` to then replace the hardcoded constants.

Alternatively, we could also do it with structs, like the AES api.

### PR DESCRIPTION
**Pull request by thomwiggers**
Closes #171

### CODE REVIEW

**Comment by joostrijneveld** [comment]
Looks good to me. Did you run tests for SPHINCS+ locally, given that CI is currently skipping them for efficiency reasons?

**Comment by thomwiggers** [comment]
Yes, on Linux. I'm currently running all tests on `lilo6`.

**Comment by thomwiggers** [comment]
```
2638 tests run in 14273.136 seconds.
55 skipped (2583 tests passed)
```
(clang-tidy was not available)

Seems like this can be merged.

**Comment by thomwiggers** [comment]
Actually: one open question:

Do we want to split the types between absorb-state and squeeze state of a XOF? Because it'd be incorrect form to pass the state back to the absorb function once you've called `finalize`...

**Comment by thomwiggers** [comment]
> Do we want to split the types between absorb-state and squeeze state of a XOF? Because it'd be incorrect form to pass the state back to the absorb function once you've called finalize...

Probably not in C. In e.g. Rust (and probably C++11+) it's easy to do define a function that _consumes_ a value and then returns a new value. In C you'd have to copy the state or do weird things with pointers to pointers... Not sure that's better semantics-wise.

**Comment by cryptojedi** [comment]
Thom Wiggers <notifications@github.com> wrote:
> Actually: one open question:
> 
> Do we want to split the types between absorb-state and squeeze state
> of a XOF? Because it'd be incorrect form to pass the state back to the
> absorb function once you've called `finalize`...

Interesting question. The type system of C is not strong enough to
really enforce this, though. As the state is really the same kind of
object, an implementation can simply cast pointer types and still do
this without triggering even warnings.

**Pull request merged**
