### PR TITLE
Fix failing emulated CI runs

### PR DESCRIPTION
**Pull request by SWilson4**
Add `--ignore-installed` to the `pip install` command for emulated builds. It's not great, but it seems to do the job.

#### Manually checked properties
* [ ] Generated Github workflow (run ``.github/workflows/generate_workflows.py``) (new schemes)
* [ ] No stringification macros
* [ ] Output-parameter pointers in functions are on the left
* [ ] Negative return values on failure of API functions (within restrictions of FO transform).
* [ ] variable declarations at the beginning (except in `for (size_t i=...`)
* Optional:
  * [ ] All integer types are of fixed size, using `stdint.h` types (including `uint8_t` instead of `unsigned char`)
  * [ ] Integers used for indexing are of size `size_t`

### CODE REVIEW

**Comment by thomwiggers** [comment]
Can you clarify what kind of error you're getting?

**Comment by thomwiggers** [comment]
I realized I can easily run the `arm64` container because I have an ARM mac now.

```
Installing collected packages: PyYAML, pycparser, jinja2
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 6.0
    Not uninstalling pyyaml at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'PyYAML'. No files were found to uninstall.
  Attempting uninstall: pycparser
    Found existing installation: pycparser 2.21
    Not uninstalling pycparser at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pycparser'. No files were found to uninstall.
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.1.2
    Not uninstalling jinja2 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Jinja2'. No files were found to uninstall.
Successfully installed PyYAML-6.0.1 jinja2-3.1.3 pycparser-2.22
```

**Comment by SWilson4** [comment]
> Can you clarify what kind of error you're getting?

Not super relevant since this is now merged and working, but all powerpc CI had been failing for some time: https://github.com/PQClean/PQClean/actions/runs/8778470071/job/24085301259#step:6:73

**Comment by thomwiggers** [comment]
Yeah looks like the same error

**Pull request merged**
