### PR TITLE
Dilithium: Update to NIST Draft Standard 

### PR DESCRIPTION
**Pull request by mkannwischer**
#### Manually checked properties
* [ ] Generated Github workflow (run ``.github/workflows/generate_workflows.py``) (new schemes)
* [ ] No stringification macros
* [ ] Output-parameter pointers in functions are on the left
* [ ] Negative return values on failure of API functions (within restrictions of FO transform).
* [ ] variable declarations at the beginning (except in `for (size_t i=...`)
* Optional:
  * [ ] All integer types are of fixed size, using `stdint.h` types (including `uint8_t` instead of `unsigned char`)
  * [ ] Integers used for indexing are of size `size_t`

### CODE REVIEW

**Comment by thomwiggers** [comment]
`test_functest.py` seems to work on M2

**Comment by thomwiggers** [comment]
I've merged https://github.com/PQClean/PQClean/pull/500. This means that there are a gajillion files in conflict but should also mean that we approach green CI a bit sooner.

**Comment by mkannwischer** [comment]
> I've merged #500. This means that there are a gajillion files in conflict but should also mean that we approach green CI a bit sooner.

I've rebased this on top of master. So I think it's ready for review now. 
Can you test the nistkat on Apple silicon as well, please? Now it should be working fine.

**Comment by thomwiggers** [comment]
Seems to work. Just checking, like the Kyber PR, this follows the reference code repository's `standard` branch, right? There are some differences I believe...

**Review by thomwiggers — DISMISSED** [review]
Scrolling through this looks convincing.

**Comment by mkannwischer** [comment]
> Seems to work. Just checking, like the Kyber PR, this follows the reference code repository's `standard` branch, right? There are some differences I believe...

Yes, indeed. This version is compatible with the https://github.com/pq-crystals/dilithium/tree/standard (commit https://github.com/pq-crystals/dilithium/commit/918af1a6eaedcedf9fdd8aaaca6c1fccd5a7a51f).

**Review by thomwiggers — APPROVED** [review]

**Pull request merged**
