### PR TITLE
Add ephemeral versions of ThreeBears

### PR DESCRIPTION
**Pull request by leonbotros**
This PR adds the ephemeral versions of ThreeBears.
The code is generated by: https://github.com/leonbotros/threebears-clean.

### CODE REVIEW

**Comment by thomwiggers** [comment]
wtf, this did work in the other PR #262  – I'll mark that one as approved and then it will be merged.

**Comment by leonbotros** [comment]
Mmh that's indeed weird.
It seems to generate memcpy/memset warnings, even on schemes I didn't touch.

**Comment by thomwiggers** [comment]
Yeah, and these errors (which do make sense, except that we don't have a C11 codebase) should be disabled by the `.clang-tidy`....

**Comment by thomwiggers** [comment]
Closed by #262

**Pull request closed without merging**
